### ISSUE TITLE
Is logged in (decorator or function?)

### ISSUE THREAD

**Issue by Woolworths** [YosaiProject/yosai_alchemystore#2]
How would I make a function protected to only logged in users?
`def protected():  
    if logged_in:
`
or 
`@logged_in  
def protected():  
    pass
`

**Comment by Dowwie** [comment]
this isn't an issue -- please ask again in the google groups so that others could benefit by the response (I'll respond in kind)  yosai@googlegroups.com

**Comment by Woolworths** [comment]
My bad. The answer turned out to be identifier.authenticated. I just missed it in the docs.

**Comment by Dowwie** [comment]
take a look at /authc/decorators.py

please email the googlegroup this question as it'll get me started writing a complete response that I'll add to the documentation
